### ISSUE TITLE
Failed setup error with MX6200

### ISSUE THREAD

**Issue by oscahie** [uvjim/linksys_velop#491]
My hardware: 3 x Linksys MX6200 nodes, running latest firmware (1.0.11.216041), configured in bridge mode.

When I add the integration to home assistant, the initial setup process goes well, I enter the master node's address, the admin password and navigate successfully through the various popups, but after the integration is created I'm always encountering this error:

`Failed setup, will retry: Unknown action URI 'http://linksys.com/jnap/healthcheck/GetHealthCheckResults'`

Last relevant lines of the debug log:

```
2024-10-30 03:14:39.285 DEBUG (MainThread) [pyvelop.mesh] _set_raw_value --> Unknown action URI 'http://linksys.com/jnap/healthcheck/GetHealthCheckResults'
2024-10-30 03:14:39.311 DEBUG (MainThread) [pyvelop.mesh] _set_raw_value --> _ErrorAbortedAction: 'http://linksys.com/jnap/healthcheck/GetHealthCheckStatus'
2024-10-30 03:14:39.334 DEBUG (MainThread) [pyvelop.mesh] _set_raw_value --> _ErrorAbortedAction: 'http://linksys.com/jnap/nodes/topologyoptimization/GetTopologyOptimizationSettings2'
2024-10-30 03:14:39.358 DEBUG (MainThread) [pyvelop.mesh] _set_raw_value --> _ErrorAbortedAction: 'http://linksys.com/jnap/nodes/firmwareupdate/GetFirmwareUpdateStatus'
2024-10-30 03:14:39.380 DEBUG (MainThread) [pyvelop.mesh] _set_raw_value --> _ErrorAbortedAction: 'http://linksys.com/jnap/routerupnp/GetUPnPSettings'
2024-10-30 03:14:39.401 DEBUG (MainThread) [pyvelop.mesh] _set_raw_value --> _ErrorAbortedAction: 'http://linksys.com/jnap/router/GetWANStatus3'
2024-10-30 03:14:39.421 DEBUG (MainThread) [pyvelop.mesh] _set_raw_value --> _ErrorAbortedAction: 'http://linksys.com/jnap/wirelessap/GetWPSServerSettings'
2024-10-30 03:14:39.442 DEBUG (MainThread) [pyvelop.mesh] _set_raw_value --> Unknown action URI 'http://linksys.com/jnap/homekit/GetHomeKitSettings'
2024-10-30 03:14:39.463 DEBUG (MainThread) [pyvelop.mesh] _set_raw_value --> Unknown action URI 'http://linksys.com/jnap/nodes/storage/GetNodesPartitions'
2024-10-30 03:14:39.483 DEBUG (MainThread) [pyvelop.mesh] _set_raw_value --> Unknown action URI 'http://linksys.com/jnap/nodes/storage/GetSMBServerSettings'
2024-10-30 03:14:39.511 DEBUG (MainThread) [pyvelop.mesh] _async_gather_details --> exited
2024-10-30 03:14:39.531 DEBUG (MainThread) [pyvelop.mesh] async_gather_details --> exited
2024-10-30 03:14:39.539 DEBUG (MainThread) [custom_components.linksys_velop] Finished fetching linksys_velop mesh (58W10M26D01971) data in 3.301 seconds (success: True)
2024-10-30 03:14:39.559 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (58W10M26D01971) --> setting up the speedtest coordinator
2024-10-30 03:14:39.580 DEBUG (MainThread) [pyvelop.mesh] async_get_speedtest_results --> entered
2024-10-30 03:14:39.599 DEBUG (MainThread) [pyvelop.mesh] _async_make_request --> entered
2024-10-30 03:14:39.620 DEBUG (MainThread) [pyvelop.jnap] Request.execute --> entered
2024-10-30 03:14:39.641 DEBUG (MainThread) [pyvelop.jnap] Request.execute --> URL: http://10.0.0.20/JNAP/, Headers: {'X-JNAP-Authorization': '**REDACTED**', 'Content-Type': 'application/json; charset=UTF-8', 'X-JNAP-Action': 'http://linksys.com/jnap/healthcheck/GetHealthCheckResults'}, Payload: {"healthCheckModule": "SpeedTest", "includeModuleResults": true, "lastNumberOfResults": 1}, Timeout: 10
2024-10-30 03:14:39.661 DEBUG (MainThread) [pyvelop.mesh] async_get_speedtest_state --> entered
2024-10-30 03:14:39.681 DEBUG (MainThread) [pyvelop.mesh] _async_gather_details --> entered, args: JNAPActionMappings.GET_SPEEDTEST_STATUS
2024-10-30 03:14:39.701 DEBUG (MainThread) [pyvelop.mesh] _async_make_request --> entered
2024-10-30 03:14:39.722 DEBUG (MainThread) [pyvelop.jnap] Request.execute --> entered
2024-10-30 03:14:39.741 DEBUG (MainThread) [pyvelop.jnap] Request.execute --> URL: http://10.0.0.20/JNAP/, Headers: {'X-JNAP-Authorization': '**REDACTED**', 'Content-Type': 'application/json; charset=UTF-8', 'X-JNAP-Action': 'http://linksys.com/jnap/core/Transaction'}, Payload: [{"action": "http://linksys.com/jnap/healthcheck/GetHealthCheckStatus", "request": {}}], Timeout: 10
2024-10-30 03:14:39.955 DEBUG (MainThread) [pyvelop.jnap.verbose] Request.execute --> action: http://linksys.com/jnap/core/Transaction --> payload: [{'action': 'http://linksys.com/jnap/healthcheck/GetHealthCheckStatus', 'request': {}}] --> response: {'result': 'Error', 'responses': [{'result': '_ErrorUnknownAction', 'error': "Unknown action URI 'http://linksys.com/jnap/healthcheck/GetHealthCheckStatus'"}]}
2024-10-30 03:14:39.979 DEBUG (MainThread) [pyvelop.jnap] Request.execute --> exited
2024-10-30 03:14:40.003 DEBUG (MainThread) [pyvelop.mesh] _async_make_request --> exited
2024-10-30 03:14:40.025 DEBUG (MainThread) [pyvelop.mesh] _set_raw_value --> Unknown action URI 'http://linksys.com/jnap/healthcheck/GetHealthCheckStatus'
2024-10-30 03:14:40.045 DEBUG (MainThread) [pyvelop.mesh] _async_gather_details --> exited
2024-10-30 03:14:40.065 DEBUG (MainThread) [pyvelop.jnap.verbose] Request.execute --> action: http://linksys.com/jnap/healthcheck/GetHealthCheckResults --> payload: {'healthCheckModule': 'SpeedTest', 'includeModuleResults': True, 'lastNumberOfResults': 1} --> response: {'result': '_ErrorUnknownAction'}
2024-10-30 03:14:40.065 WARNING (MainThread) [custom_components.linksys_velop.coordinator] A currently uncaught exception was encountered, type: <class 'KeyError'>, msg: 8192
2024-10-30 03:14:40.066 DEBUG (MainThread) [custom_components.linksys_velop] Finished fetching linksys_velop speedtest (58W10M26D01971) data in 0.506 seconds (success: False)
```

I'm using version 2024.10.1. Let me know if you need full logs.

**Comment by uvjim** [comment]
Hi, should be a relatively easy fix upstream. One question though, that endpoint checks the status of the Speedtest functionality; is the Speedtest option greyed out in the Linksys app or web UI?

**Comment by oscahie** [comment]
Hey, the speed test option is shown in the Linksys app but when I start the test it rapidly appears to fail and just shows a "Try running it again" error message. I don't see any speed test option in the web UI though.

So maybe this is an issue in Linksys' end? Hopefully the error can be ignored upstream anyway.

**Comment by uvjim** [comment]
Not an error. It's by design from Linksys (so I'm surprised they don't handle it better).

![Screenshot_20241030_071828_DuckDuckGo.png](https://github.com/user-attachments/assets/483b26cb-09f8-4cf1-825f-fe0430d69e77)

The weird thing is that not all things in that list get disabled. Anyway, I'll add it to the list of "unsafe" endpoints.

Unsafe endpoints, in terms of `pyvelop` are those that may not work on all devices. So, when an error is found calling one of them, it gets ignored.

**Comment by oscahie** [comment]
Yeah that's something that upsets me since the moment I bought these nodes, how they disable a lot of features that could work perfectly while in bridge mode! As it stands my mesh system is just a WiFi access point and that's it, zero additional functionality 😠 Disabling speed test too is extra silly but I couldn't care less about it.

Looking forward to your fix. I'm hoping to be able to use the device trackers functionality for some presence sensing I need, mainly.

**Comment by uvjim** [comment]
I've reopened this.  It was a bit eager to be closed.  I have pushed the change upstream, but it won't be available to the integration until I bump the `pyvelop` version.  I'll hopefully do that later tonight.

**Comment by uvjim** [comment]
Should be fixed by #492 which was released in https://github.com/uvjim/linksys_velop/tree/2024.10.2
Feel free to re-open if it hasn't resolved the issue.

**Comment by oscahie** [comment]
I'm sorry to report that I still see the same issue with 2024.10.2. Exact same error, and I've even tried deleting and re-adding the integration 🤔

**Comment by uvjim** [comment]
Hmmm... Sorry about that.  Let me have a look through the log again.  There could be more than just the one action that I was looking at.

**Comment by uvjim** [comment]
Also, are you familiar with using Postman?  If so, could I give you a couple of commands to execute that might help me better detect bridged mode and automatically adjust the request made based on that?

**Comment by oscahie** [comment]
Attached a debug log. [linksys_velop_debug.log](https://github.com/user-attachments/files/17580236/linksys_velop_debug.log)

I'm familiar with Postman, happy to help!

**Comment by uvjim** [comment]
I think I see what is happening now. 
Could you send a diagnostics log from the integration in Home Assistant please? Hopefully that will let me confirm my thoughts. 
However there are a couple of issues that do need to be resolved. 
Also, do you have any entities enabled that relate to Speedtest, e.g. a button, sensor or binary sensor?

**Comment by oscahie** [comment]
Isn't the log I attached in my previous message what you're asking for? Otherwise I'm not sure what you mean by diagnostics log.

When I add the integration I just proceed with the default options, I'm not adding any trackers nor devices. And in home assistant I don't have anything related to speedtesting.

**Comment by uvjim** [comment]
Diagnostics: https://github.com/uvjim/linksys_velop#diagnostics-integration

There seems to be a few problems happening at the same time when in bridge mode.

1. Reports it's not a primary node so aborts all the other queries.
2. Attempts to setup the Speedtest coordinator when it possibly shouldn't because as we know Speedtest isn't available in bridge mode.

I don't use a bridge here... In fact I found a spare node and tried to see if I could set it up and it sends my network into an odd state, which I've had to recover from twice now.

The diagnostics will possibly help me understand if it the Velop thinks there's a device that is a primary node. If there is, then we can start by using that one. If there isn't then I'm at a loss as to where to direct requests to if it's going to tell me it's not a primary node and then abort all other queries in that transaction.

I may need to put a small piece of logic in to detect that node is in bridge mode then decide which queries to use.

**Comment by oscahie** [comment]
I see, but since the integration setup fails, a mesh device is never really created, so I don't have access to that screen with the diagnostics log link. Is perhaps the log generated via `http://<node-ip>/sysinfo.cgi` what you need?

I do enter the primary node's details in the setup process so I'm not sure why it reports otherwise.

**Comment by uvjim** [comment]
That's fine. I have started work on detecting the capabilities that the Mesh supports in the upstream library. Hopefully that will help us get to the bottom of this.

If it's OK, I may need you to download `pyvelop` and run the CLI so we can see what is happening. It's a Linux only CLI mind you. Does that cause a problem?

**Comment by oscahie** [comment]
Yeah no problem, I have pyvelop working on my mac now.

**Comment by uvjim** [comment]
Thanks for your patience... I have pushed `pyvelop` version `2024.11.1b0` to GitHub now.  You can find it here: https://github.com/uvjim/pyvelop/releases/tag/2024.11.1b0

Would you be able to give that a try please.  If you issue the following command.  If you could ask the CLI to gather details about the mesh, it should give you some information.  The new piece should give you a list of "capabilities" (see screenshot below).  If you could send me a screenshot of the capabilities you get from your Velop, that would be great.

![image](https://github.com/user-attachments/assets/9ea6add2-5ff1-44ed-a5ee-b6fe30141488)

I'm hoping I can then use those, to make the creation of entities, and gathering details more dynamic for what the mesh offers.

As I said, I don't have the Velop running in bridge mode here, so I never really built it with that in mind.

**Comment by oscahie** [comment]
Thanks a lot for your support!

I might be doing something wrong but I downloaded 2024.11.1b0 and when I run it like this:

`python3.11 -m pyvelop mesh details -a <node_ip>` 

it asks for the password and after about 5 seconds it ends without outputting anything at all. I tried passing `--verbose' and it didn't help.

**Comment by uvjim** [comment]
Probably not doing anything wrong. The CLI doesn't do much error checking.

Instead of --verbose, could you try -vvvv?

That might give me a clue as to what is happening. Ifnyoubcouldnpaste the output here (preferably in an attachment) - you may want to redact some information in there.

**Comment by oscahie** [comment]
There you go: [output.txt](https://github.com/user-attachments/files/17597603/output.txt)

**Comment by uvjim** [comment]
Thanks for that. I can see the capabilities now. I'll work on fixing the CLI properly (should've done that before I made the repo public really).

Once we have the data visible to you in there and we know it's right, I can release and start adjusting the integration to use this new feature.

I know what is happening on the integration side as well, it's trying to set up the coordinator for Speedtest even though you don't have that capability. In addition it's actually asking for that data before creating the entities - normally fine, but clearly not when it isn't going to work anyway.

We'll get there. The good news is, the devices JNAP action is actually responding despite what the Linksys documentation (if you can call it that) states.

**Comment by uvjim** [comment]
Hello... thanks for your patience with this.  I have now pushed another beta for `pyvelop`.  It can be found here: https://github.com/uvjim/pyvelop/releases/tag/2024.11.1b1

Hopefully, the CLI output has been cleaned up with better error exception handling as well.  It seems to be working fine here, but I'm not in bridge mode as you know.

**Comment by oscahie** [comment]
Impressive turn around time, thanks :) 

So `mesh details` now works correctly. Attached the [output](https://github.com/user-attachments/files/17604723/output.txt). Also tried `node details` and it seems to work too though initially I thought it wasn't but turns out I was missing one upper-cased letter. Maybe this could be made case insensitive.

The one odd little detail I noticed is that my iPhone is listed in the log within the offline group while it's definitely connected to the mesh 🤔 I hope this is not an early indicator that device tracking is not going to be very reliable with these nodes in bridge mode, but we shall see.

**Comment by uvjim** [comment]
Thanks for testing that... Notes about the Node names, I'll make it case insensitive.

RE: the iPhone. Do any of the online devices have the same IP as your iPhone? It sounds like a daft question, but I have seen occasions where a device is shown offline because the Velop has decided it's a new device. When this happens it gets a new unique id and doesn't have any of the same information (it thinks it's new and different so why would it). I'm not 100% what makes them think it's new but I have a feeling it could be to do with randomising MAC addresses when connecting to networks (a feature which both iOS and Android offer now).

I'm going to assume that neither the Linksys app nor web UI allow you to see the device list when in bridge mode. If either one of them does, could you check in there and see if they show the same? It could be that it uses a modified JNAP action in bridged mode.

**Comment by oscahie** [comment]
No, I checked my iPhone's assigned IP address and it wasn't on the list of connected devices provided by your tool. Of course neither the Linksys app nor their web UI provide this listing, the only other thing where I can possibly look at connected devices is the /sysinfo.cgi log for each node.

**Comment by uvjim** [comment]
Hmmm... Does it appear as connected in sysinfo then? If so, I can look at parsing that and merging the results in.

**Comment by oscahie** [comment]
Yes, that log is huge and my iPhone's mac address appears in a couple of tables listing connected clients, including which node each client is connected to. But downsides of this approach would be that 1) generating the log is pretty slow and 2) it'd be messy and probably brittle to parse as it seems to be just a concatenation of the outputs of multiple different commands, each with their own sort of format.

Anyway, lets see first how device tracking actually works on the current integration. Looking forward to see what else is exposed.

**Comment by uvjim** [comment]
Right, I've pushed a beta for the integration now which incorporates the functionality added into `pyvelop`.  If you're using HACS you'll need to make sure that you're seeing betas as well.  If not, the link is here: https://github.com/uvjim/linksys_velop/releases/tag/2024.11.1b0

Let me know how you get on.

**Comment by oscahie** [comment]
Thanks! So on the latest [2024.11.1b1](https://github.com/uvjim/linksys_velop/releases/tag/2024.11.1b1) I can add the integration successfully and it creates node devices, mesh device and a bunch entities. Most of the entities seem to report the right thing, but still need to play some more with the device tracking as e.g. the list of devices reported by sensor.mesh_online_devices is way smaller than it really is, and most devices do not appear to report their ip nor mac address.

There's what appears to be a code issue though: when I tap configure over an existing hub, all of the pop-up menu options report an error. For instance if I tap the device trackers entry, I see this exception in the log:

```
2024-11-05 01:41:30.033 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_device_trackers --> entered, user_input: None
2024-11-05 01:41:30.077 DEBUG (MainThread) [pyvelop.mesh] __init__ --> entered
2024-11-05 01:41:30.113 DEBUG (MainThread) [pyvelop.mesh] __init__ --> Session was passed in: Yes
2024-11-05 01:41:30.143 DEBUG (MainThread) [pyvelop.mesh] __init__ --> pyvelop version: 2024.11.1
2024-11-05 01:41:30.170 DEBUG (MainThread) [pyvelop.mesh] __init__ --> Initialised mesh for 10.0.0.20
2024-11-05 01:41:30.195 DEBUG (MainThread) [pyvelop.mesh] __init__ --> exited
2024-11-05 01:41:30.195 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 285, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linksys_velop/config_flow.py", line 701, in async_step_device_trackers
    self._devices = await _async_get_devices(mesh=mesh)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linksys_velop/config_flow.py", line 271, in _async_get_devices
    devices: list[Device] = await mesh.async_get_devices()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyvelop/decorators.py", line 20, in wrapper
    raise MeshNeedsInitialise from None
pyvelop.exceptions.MeshNeedsInitialise: You must call the initialise method first
```

Side note: I wish there was a way to set a custom prefix for all entity ids created by the integration, as using only the node name as prefix can lead to somewhat confusing and non-descriptive enough ids, the result being a bit messy IMHO. At least I particularly like to keep my ids sort of namespaced to make it easier to work with them in automations and such.

**Comment by uvjim** [comment]
Simple enough fix for the traceback (I just missed an adaptation for the new version of `pyvelop`)

Do you know any other integrations that prefix entity IDs? None of the built-in ones do. The `entity_id` is typically a slugified version of the name. The name shouldn't include the device name or the integration name as far as I'm aware.

https://developers.home-assistant.io/blog/2022/07/10/entity_naming/

https://developers.home-assistant.io/docs/core/entity#entity-naming

**Comment by uvjim** [comment]
The fix for the traceback should be in https://github.com/uvjim/linksys_velop/releases/tag/2024.11.1b2
I'll close this one as we seem to be past the setup error now.  Anything else can be handled in separate issues.

**Comment by oscahie** [comment]
I can confirm the integration can be configured correctly. Unfortunately device tracking does not seem work relkiably at all, I added the device that correspond's to my iPhone's WiFi mac, and it's reportedly changing often between home and away while I haven't moved from home. Do you think it's worth opening a separate issue to try and find out what's going on or is it maybe a lost case when the bridge mode doesn't officially support device listing?
